'use client'

import { useRef, useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { Lightbox, type LightboxImage } from '@/components/lightbox'

interface ShowcaseProps {
  images: LightboxImage[]
}

/**
 * 首页 showcase：横向 carousel，左右箭头点击滚动一张（不自动滚）。
 * 点图进全屏 Lightbox。仅在未登录落地页渲染。
 */
export function Showcase({ images }: ShowcaseProps) {
  const [index, setIndex] = useState<number | null>(null)
  const scrollRef = useRef<HTMLDivElement>(null)

  const scrollByCard = (dir: 1 | -1) => {
    const el = scrollRef.current
    if (!el) return
    // 滚动一张卡片的宽度（含 gap-4 = 16px）
    const card = el.querySelector<HTMLElement>('[data-card]')
    const distance = card ? card.offsetWidth + 16 : el.clientWidth * 0.8
    el.scrollBy({ left: dir * distance, behavior: 'smooth' })
  }

  return (
    <section id="examples" className="mt-20 scroll-mt-20">
      <div className="mx-auto max-w-5xl px-4">
        <h2 className="text-center text-2xl font-bold tracking-tight sm:text-3xl">
          Real tattoo previews
        </h2>
        <p className="mx-auto mt-2 max-w-md text-center text-sm text-muted-foreground">
          Generated by AI · click to enlarge
        </p>

        <div className="relative mt-8">
          {/* 左箭头 */}
          <button
            type="button"
            onClick={() => scrollByCard(-1)}
            aria-label="Scroll left"
            className="absolute left-0 top-1/2 z-10 -translate-y-1/2 rounded-full bg-background/80 p-2 shadow ring-1 ring-border backdrop-blur transition hover:bg-background"
          >
            <ChevronLeft className="h-6 w-6" />
          </button>

          {/* 横向滚动容器：4 张横排，snap 对齐，隐藏原生滚动条 */}
          <div
            ref={scrollRef}
            className="flex snap-x snap-mandatory gap-4 overflow-x-auto scroll-smooth pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
          >
            {images.map((img, i) => (
              <button
                key={img.url}
                type="button"
                data-card
                onClick={() => setIndex(i)}
                aria-label={img.alt}
                className="relative aspect-[3/4] w-[80%] flex-shrink-0 snap-start overflow-hidden rounded-lg bg-muted sm:w-[40%]"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={img.url}
                  alt={img.alt}
                  className="h-full w-full cursor-zoom-in object-cover"
                />
              </button>
            ))}
          </div>

          {/* 右箭头 */}
          <button
            type="button"
            onClick={() => scrollByCard(1)}
            aria-label="Scroll right"
            className="absolute right-0 top-1/2 z-10 -translate-y-1/2 rounded-full bg-background/80 p-2 shadow ring-1 ring-border backdrop-blur transition hover:bg-background"
          >
            <ChevronRight className="h-6 w-6" />
          </button>
        </div>
      </div>

      <Lightbox
        images={images}
        index={index}
        onClose={() => setIndex(null)}
        onIndexChange={setIndex}
      />
    </section>
  )
}
