'use client'

import { useRef, useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { Lightbox, type LightboxImage } from '@/components/lightbox'

interface ShowcaseProps {
  images: LightboxImage[]
}

/**
 * 首页 showcase：横向 carousel，4 张横排（桌面近完整展示），
 * 左右圆形按钮点击循环滚动（末尾绕回开头），不自动滚。
 * 苹果风格排版：大圆角卡片 + 阴影 + ring + hover 微放大。
 * 点图进全屏 Lightbox。仅在未登录落地页渲染。
 */
export function Showcase({ images }: ShowcaseProps) {
  const [index, setIndex] = useState<number | null>(null)
  const scrollRef = useRef<HTMLDivElement>(null)

  const scrollByCard = (dir: 1 | -1) => {
    const el = scrollRef.current
    if (!el) return
    const card = el.querySelector<HTMLElement>('[data-card]')
    const distance = card ? card.offsetWidth + 20 /* gap-5 */ : el.clientWidth * 0.85
    const maxScroll = el.scrollWidth - el.clientWidth
    let target = el.scrollLeft + dir * distance
    // 循环：到末尾绕回开头 / 到开头绕到末尾
    if (target >= maxScroll - 4) target = 0
    else if (target <= 4) target = maxScroll
    el.scrollTo({ left: target, behavior: 'smooth' })
  }

  return (
    <section id="examples" className="mt-24 scroll-mt-20">
      <div className="mx-auto max-w-6xl px-4">
        <h2 className="text-center text-3xl font-semibold tracking-tight text-balance sm:text-4xl">
          Real tattoo previews
        </h2>
        <p className="mx-auto mt-3 max-w-md text-center text-base text-muted-foreground text-pretty">
          Generated by AI · click to enlarge
        </p>

        <div className="relative mt-12">
          {/* 左箭头（半浮在容器外，苹果风格） */}
          <button
            type="button"
            onClick={() => scrollByCard(-1)}
            aria-label="Previous images"
            className="absolute left-0 top-1/2 z-10 flex size-11 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-background shadow-xl ring-1 ring-border transition hover:scale-110 sm:size-12"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>

          {/* 横向滚动：snap 对齐，隐藏原生滚动条 */}
          <div
            ref={scrollRef}
            className="flex snap-x snap-mandatory gap-5 overflow-x-auto scroll-smooth px-2 pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
          >
            {images.map((img, i) => (
              <button
                key={img.url}
                type="button"
                data-card
                onClick={() => setIndex(i)}
                aria-label={img.alt}
                className="group relative aspect-[3/4] w-[85%] flex-shrink-0 snap-center overflow-hidden rounded-2xl bg-muted shadow-lg ring-1 ring-black/5 transition-transform duration-300 hover:scale-[1.03] sm:w-[24%]"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={img.url}
                  alt={img.alt}
                  className="h-full w-full cursor-zoom-in object-cover transition-transform duration-500 group-hover:scale-105"
                />
              </button>
            ))}
          </div>

          {/* 右箭头 */}
          <button
            type="button"
            onClick={() => scrollByCard(1)}
            aria-label="Next images"
            className="absolute right-0 top-1/2 z-10 flex size-11 translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-background shadow-xl ring-1 ring-border transition hover:scale-110 sm:size-12"
          >
            <ChevronRight className="h-5 w-5" />
          </button>
        </div>
      </div>

      <Lightbox
        images={images}
        index={index}
        onClose={() => setIndex(null)}
        onIndexChange={setIndex}
      />
    </section>
  )
}
