'use client'

import { useState } from 'react'
import { Lightbox, type LightboxImage } from '@/components/lightbox'

interface ShowcaseProps {
  images: LightboxImage[]
}

/**
 * 首页 showcase：3 列网格示例图，点击进全屏 Lightbox（串联切换）。
 * 仅在未登录落地页渲染（由 page.tsx 的 <Show when="signed-out"> 控制）。
 */
export function Showcase({ images }: ShowcaseProps) {
  const [index, setIndex] = useState<number | null>(null)

  return (
    <section id="examples" className="mt-20 scroll-mt-20">
      <div className="mx-auto max-w-5xl px-4">
        <h2 className="text-center text-2xl font-bold tracking-tight sm:text-3xl">
          Real tattoo previews
        </h2>
        <p className="mx-auto mt-2 max-w-md text-center text-sm text-muted-foreground">
          Generated by AI · click to enlarge
        </p>

        <div className="mt-8 grid grid-cols-3 gap-3 sm:gap-4">
          {images.map((img, i) => (
            <button
              key={img.url}
              type="button"
              onClick={() => setIndex(i)}
              aria-label={img.alt}
              className="group relative block aspect-[3/4] overflow-hidden rounded-lg bg-muted"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={img.url}
                alt={img.alt}
                className="h-full w-full cursor-zoom-in object-cover transition-transform duration-200 group-hover:scale-[1.02]"
              />
            </button>
          ))}
        </div>
      </div>

      <Lightbox
        images={images}
        index={index}
        onClose={() => setIndex(null)}
        onIndexChange={setIndex}
      />
    </section>
  )
}
